import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import { defineConfig, type Plugin } from 'vite';

/**
 * `theme.css` is a plain stylesheet, so TypeScript has no type for it and
 * `import '@trailpack-ui/theme/theme.css'` would fail with TS2882. A stub next to
 * it is what the `types` condition of that export points at.
 */
function stylesheetTypeStub(): Plugin {
  return {
    name: 'trailpack-stylesheet-type-stub',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'theme.css.d.ts',
        source: `// Generated by vite.config.ts, so \`import '…/theme.css'\` resolves to a
// type instead of failing with TS2882.
export {};
`,
      });
    },
  };
}

export default defineConfig({
  plugins: [vanillaExtractPlugin(), stylesheetTypeStub()],
  build: {
    sourcemap: true,
    lib: {
      entry: { index: 'src/index.ts' },
      formats: ['es'],
      // The stylesheet name is public API — it is an export path in
      // package.json — so it must not be derived from the entry name.
      cssFileName: 'theme',
    },
    // Nothing may be hashed, for the same reason.
    rollupOptions: { output: { assetFileNames: '[name][extname]' } },
  },
});
