import { fileURLToPath } from 'node:url';
import { rootLayer } from '@trailpack-ui/theme';
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import type { Plugin } from 'vite';
import { defineConfig } from 'vitest/config';

/**
 * Puts everything the package emits in one cascade layer, so an app's own CSS —
 * unlayered, and therefore ahead of any layer whatever its specificity — can
 * restyle a component through `className`.
 *
 * Applied to the bundle rather than to each rule: `style`, `styleVariants` and
 * `globalStyle` would each need a wrapper that carries the layer, one that a
 * new stylesheet can forget, and anything a vanilla-extract extension generates
 * internally (`recipes`, `sprinkles`) calls `style` where no wrapper reaches.
 * The bundle is the one place every rule has to pass through.
 */
const cascadeLayer = (): Plugin => {
  return {
    name: 'trailpack-cascade-layer',
    // Vite's own CSS plugin emits the stylesheet in `generateBundle` as well.
    // Without `post` this one runs first and there is no asset to wrap yet.
    enforce: 'post',
    generateBundle(_options, bundle) {
      const stylesheet = bundle['styles.css'];

      // Loud on purpose: unlayered styles look exactly right here and only
      // fail in an app, as a component that ignores the class it was given.
      if (stylesheet?.type !== 'asset' || typeof stylesheet.source !== 'string') {
        return this.error(
          'No styles.css asset to wrap — the package would ship outside its layer.',
        );
      }

      stylesheet.source = `@layer ${rootLayer}.components{${stylesheet.source}}`;
    },
  };
};

/**
 * `styles.css` is a plain stylesheet, so TypeScript has no type for it and
 * `import '@trailpack-ui/react/styles.css'` would fail with TS2882. A stub next
 * to it is what the `types` condition of that export points at.
 */
const stylesheetTypeStub = (): Plugin => {
  return {
    name: 'trailpack-stylesheet-type-stub',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'styles.css.d.ts',
        source: `// Generated by vite.config.ts, so \`import '…/styles.css'\` resolves to a
// type instead of failing with TS2882.
export {};
`,
      });
    },
  };
};

export default defineConfig({
  plugins: [vanillaExtractPlugin(), stylesheetTypeStub(), cascadeLayer()],
  test: {
    // The vanilla-extract plugin above is what lets a test import a component
    // that pulls in a `.css.ts`; without it the import fails outright.
    environment: 'happy-dom',
    setupFiles: ['./src/tests/setup.ts'],
    alias: {
      '@tests': fileURLToPath(new URL('./src/tests', import.meta.url)),
    },
  },
  build: {
    sourcemap: true,
    lib: {
      // One per code `exports` entry in package.json; tsconfig.build.json lists
      // the same three, or the subpath ships without declarations.
      entry: {
        index: 'src/index.ts',
        'components/index': 'src/components/index.ts',
        'utils/index': 'src/utils/index.ts',
      },
      formats: ['es'],
      cssFileName: 'styles',
    },
    rollupOptions: {
      // The peers stay out of the bundle; `react/jsx-runtime` is pulled in by
      // the automatic JSX transform rather than by any import we write.
      external: ['react', 'react/jsx-runtime', /^@trailpack-ui\/theme/],
      output: {
        assetFileNames: '[name][extname]',
        // One output file per source module, so a `'use client'` marks only
        // the module that needs it. Bundled into a single file there would be
        // one directive for the whole package, and every component would land
        // in the consumer's client bundle.
        preserveModules: true,
        preserveModulesRoot: 'src',
        entryFileNames: '[name].js',
      },
    },
  },
});
