import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import { defineConfig, type Plugin } from 'vite';

/**
 * `styles.css` is a plain stylesheet, so TypeScript has no type for it and
 * `import '@trailpack-ui/react/styles.css'` would fail with TS2882. A stub next
 * to it is what the `types` condition of that export points at.
 */
const stylesheetTypeStub = (): Plugin => {
  return {
    name: 'trailpack-stylesheet-type-stub',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'styles.css.d.ts',
        source: `// Generated by vite.config.ts, so \`import '…/styles.css'\` resolves to a
// type instead of failing with TS2882.
export {};
`,
      });
    },
  };
};

export default defineConfig({
  plugins: [vanillaExtractPlugin(), stylesheetTypeStub()],
  build: {
    sourcemap: true,
    lib: {
      entry: { index: 'src/index.ts' },
      formats: ['es'],
      cssFileName: 'styles',
    },
    rollupOptions: {
      // The peers stay out of the bundle; `react/jsx-runtime` is pulled in by
      // the automatic JSX transform rather than by any import we write.
      external: ['react', 'react/jsx-runtime', /^@trailpack-ui\/theme/],
      output: {
        assetFileNames: '[name][extname]',
        // One output file per source module, so a `'use client'` marks only
        // the module that needs it. Bundled into a single file there would be
        // one directive for the whole package, and every component would land
        // in the consumer's client bundle.
        preserveModules: true,
        preserveModulesRoot: 'src',
        entryFileNames: '[name].js',
      },
    },
  },
});
