import { fileURLToPath } from 'node:url';
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import type { Plugin } from 'vite';
import { defineConfig } from 'vitest/config';

/**
 * `styles.css` is a plain stylesheet, so TypeScript has no type for it and
 * `import '@trailpack-ui/react/styles.css'` would fail with TS2882. A stub next
 * to it is what the `types` condition of that export points at.
 */
const stylesheetTypeStub = (): Plugin => {
  return {
    name: 'trailpack-stylesheet-type-stub',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'styles.css.d.ts',
        source: `// Generated by vite.config.ts, so \`import '…/styles.css'\` resolves to a
// type instead of failing with TS2882.
export {};
`,
      });
    },
  };
};

export default defineConfig({
  plugins: [vanillaExtractPlugin(), stylesheetTypeStub()],
  test: {
    // The vanilla-extract plugin above is what lets a test import a component
    // that pulls in a `.css.ts`; without it the import fails outright.
    environment: 'happy-dom',
    setupFiles: ['./src/tests/setup.ts'],
    alias: {
      '@tests': fileURLToPath(new URL('./src/tests', import.meta.url)),
    },
  },
  build: {
    sourcemap: true,
    lib: {
      // One per `exports` entry in package.json; tsconfig.build.json lists the
      // same four, or the subpath ships without declarations.
      entry: {
        index: 'src/index.ts',
        'components/index': 'src/components/index.ts',
        'utils/index': 'src/utils/index.ts',
      },
      formats: ['es'],
      cssFileName: 'styles',
    },
    rollupOptions: {
      // The peers stay out of the bundle; `react/jsx-runtime` is pulled in by
      // the automatic JSX transform rather than by any import we write.
      external: ['react', 'react/jsx-runtime', /^@trailpack-ui\/theme/],
      output: {
        assetFileNames: '[name][extname]',
        // One output file per source module, so a `'use client'` marks only
        // the module that needs it. Bundled into a single file there would be
        // one directive for the whole package, and every component would land
        // in the consumer's client bundle.
        preserveModules: true,
        preserveModulesRoot: 'src',
        entryFileNames: '[name].js',
      },
    },
  },
});
